### PR TITLE
Create LICENSE.md

### PR DESCRIPTION
**Pull request by ScottWeinstein**
#5 , for the lawyers

### CODE REVIEW

**Comment by nylen** [comment]
do we really need this given that the license is spelled out in `package.json`?

**Comment by ScottWeinstein** [comment]
It helps. "BSD" is ambiguous, including the text of the license in the repo removes the ambiguity

**Comment by nylen** [comment]
`package.json` uses [SPDX license IDs](https://spdx.org/licenses/) so specifying a correct ID is a better way to resolve the ambiguity.  Including the license text is fine too.  Which BSD license did you choose?  @mikeal any preference?

**Comment by ScottWeinstein** [comment]
Using a SPDX lic id will help, but that doesn't help the original poster of issue #5

**Comment by nylen** [comment]
Which BSD license did you choose?

**Pull request closed without merging**
