### PR TITLE
Fixed Swap to NOT Delete Existing Headers, and Added Tests.

### PR DESCRIPTION
**Pull request by ttahmouch**

### CODE REVIEW

**Comment by ttahmouch** [comment]
Fixed #24 .

**Comment by tonybadguy** [comment]
@mikeal Will the be merged? I also ran into the same prob.

**Comment by mikeal** [comment]
It has been a long time since I was in this code and I'd like another set of eyes also reviewing it because small changes can have a pretty big impact. Who wrote the `swap` method?

**Comment by tonybadguy** [comment]
Looks like you added swap in 2014 https://github.com/request/caseless/commit/fb6a024574fe363915afab244a038918aa158123#diff-168726dbe96b3ce427e7fedce31bb0bcR37

I just reviewed the change and the only implication is that if someone was using the swap method as a way to delete, then it would no longer work for them.

**Comment by XVincentX** [comment]
@mikeal Any chance to publish a new version with this change?

**Comment by mikeal** [comment]
v0.12.0

**Pull request merged**
